server:
  port: 8080

spring:
  profiles:
    active: dev
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  expiration:
    time: 1800000

---

spring:
  profiles:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/monyia
    username: postgres
    password: postgres

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.cllynaxcuywshbpfvdge.supabase.co:5432/postgres
    username: postgres
    password: 20kzZPk01jXyyosY
